# encoding: utf8

class PylolException(Exception):
    '''Base class for all exceptions generated by PyLoL'''
    pass

class APIFailure(PylolException):
    '''Thrown when an API request returns success = false'''

    def __init__(self, msg, path, url):
        self.msg = msg
        self.path = path
        self.url = url

class APIInvalidData(PylolException):
    '''Thrown when the API returns invalid/corrupted JSON data'''

    def __init__(self, data):
        self.msg = u'API returned invalid JSON data.'
        self.data = data

class APISummonerNotFound(PylolException):
    '''Thrown when requesting info on a summoner that doesn't exist'''

    def __init__(self, name, region):
        self.msg = u'"%s" not found on %s server.' % (name, region.upper())
        self.name = name
        self.region = region

class APISummonerIDNotFound(PylolException):
    '''Thrown when requesting info on a summoner ID that doesn't exist'''

    def __init__(self, sid, region):
        self.msg = u'Summoner %d not found.' % (sid, region.upper())
        self.sid = sid
        self.region = region

class APIInvalidRegion(PylolException):
    '''Thrown when an invalid region is specified during an API query'''

    def __init__(self, region):
        self.msg = u'%s is not a valid region.' % region
        self.region = region
